apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tp7-kustomize
resources:
  - ../base
images:
  - name: ghcr.io/1223812789/spring-petclinic
    newTag: 4.0.1-SNAPSHOT
patches:
  - path: replicas.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: petclinic
  - path: patch-routing.yaml
