apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiWU9VUl9HSVRIVUJfVVNFUk5BTUUiLCJwYXNzd29yZCI6IlJFUExBQ0VfV0lUSF9QRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJhdXRoIjoiV1U5VlVsOUhTVlJJVlVKZlZWTkZVazVCVFVVNlVrVlFURUZEUlY5WFNWUklYMUJGVWxOUFRrRk1YMEZEUTBWVFUxOVVUMHRGVGc9PSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
